spring:
  application:
    name: oauth
---
spring:
  config:
    activate:
      on-profile: default
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_INTERNAL_HOST}:${KEYCLOAK_INTERNAL_PORT}/realms/${KEYCLOAK_REALM}
      client:
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_INTERNAL_HOST}:${KEYCLOAK_INTERNAL_PORT}/realms/${KEYCLOAK_REALM}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            authorization-grant-type: ${KEYCLOAK_GRANT_TYPE}
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid