openapi: 3.0.0
info:
  title: OAuth API
  version: 1.0.0
  description: API para gerenciamento de usuários com autenticação via Keycloak.
servers:
  - url: http://localhost:8001
paths:
  /auth/login:
    post:
      summary: Efetuar login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin@pucrs.br
                password:
                  type: string
                  example: a12345678
      responses:
        '200':
          description: Login bem-sucedido
        '400':
          description: Bad Request
        '401':
          description: Unauthorized

  /auth/users:
    post:
      summary: Criar usuário
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: me@gmail.com
                firstName:
                  type: string
                  example: usuario
                lastName:
                  type: string
                  example: novo
                credentials:
                  type: array
                  items:
                    type: object
                    properties:
                      value:
                        type: string
                        example: abc123
      responses:
        '201':
          description: Usuário criado com sucesso
        '400':
          description: Bad Request
        '401':
          description: Unauthorized

    get:
      summary: Retorna a lista de todos os usuários
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de usuários retornada com sucesso
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /auth/users/{id}:
    get:
      summary: Retorna o usuário com o id especificado
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID do usuário a ser retornado
          schema:
            type: string
      responses:
        '200':
          description: Usuário encontrado
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

    put:
      summary: Atualiza o usuário com o id especificado
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID do usuário a ser atualizado
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  example: Novo Nome
                lastName:
                  type: string
                  example: Novo Sobrenome
      responses:
        '200':
          description: Usuário atualizado com sucesso
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

    delete:
      summary: Desabilita o usuário com o id especificado
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID do usuário a ser desabilitado
          schema:
            type: string
      responses:
        '204':
          description: Usuário desabilitado com sucesso
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

    patch:
      summary: Atualiza a senha do usuário com o id especificado
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID do usuário cuja senha será atualizada
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: novaSenhaSegura123
      responses:
        '200':
          description: Senha atualizada com sucesso
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
