FROM gradle:jdk21-alpine

# Set the working directory
WORKDIR /app

# Copy the Gradle wrapper and pom.xml
COPY settings.gradle ./
COPY build.gradle ./

COPY src ./src

# Build the project
RUN gradle clean build

EXPOSE 8080

COPY ./build/libs/*.jar ./oauth.jar
CMD ["java", "-jar", "oauth.jar"]